stages:
  - build
  - test
  - upload


build:
  image: node:latest
  stage: build
  script:
    - cd Trailmates
    - npm install -g @angular/cli
    - npm install
    - ng build
    - echo "Building was successful" 
  artifacts:
    paths:
      - "Trailmates/dist/"
      - "Trailmates/node_mondules/"


# test:
#   image: node:latest
#   stage: build
#   script:
#     - cd Trailmates
#     - npm install -g @angular/cli
#     - npm install
#     - ng test
#     - echo "Test was successful" 

# test:
#     stage: test
#     image: weboaks/node-karma-protractor-chrome:headless
#     script:
#         - cd Trailmates
#         - npm install --silent
#         - sudo apt-get install xvfb 
#         - xvfb-run --auto-servernum npm run test
#         # - npm run pree2e
#         # - npm run e2e
#     tags:
#         - docker 

upload to s3:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  stage: upload
  script:
    - aws configure set region us-east-1
    - cd ./Trailmates/dist/trailmates
    - aws s3 rm --recursive s3://$S3_BUCKET/
    - aws s3 cp . s3://$S3_BUCKET/ --recursive
