# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Node
      uses: actions/setup-node@v3

    - name: Use Node.js
      working-directory: ./Trailmates
      run: npm install

    - name: Unit testing
      working-directory: ./Trailmates
      run: npm test

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        start: npm run start
        working-directory: ./Trailmates
        wait-on: 'http://localhost:4200'
        wait-on-timeout: 120
    
    - name: See if it can build
      working-directory: ./Trailmates
      run: npm install